// Copyright (C) 2026 Postquant Labs Incorporated
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Cross-implementation conformance harness for the XQVM toolchain.
//!
//! Each conformance vector is a directory under `conformance/vectors/` of
//! the form `<category>/<name>/` containing:
//!
//! - `program.xqasm` — assembly source (canonical, human-readable).
//! - `inputs.json` — `{"calldata": [i64, ...]}`.
//! - `expected.json` — `{"outputs": [i64|null, ...], "final_stack": [i64, ...]}`.
//!
//! The harness assembles `program.xqasm` in-process for every run.
//! Encoding correctness is owned by the `xqasm` crate's own test suite,
//! so no pre-assembled bytecode artifact is committed.
//!
//! The Rust runner ([`run_rust`]) executes the program in-process via
//! [`xqvm::Vm`]. The Python runner ([`run_python`]) shells out to
//! `uv run python -m xqvm_py run`. Both produce an [`Outcome`] that
//! is compared against the vector's expected.json.
//!
//! Tests are generated by `build.rs` — one `#[test]` per vector per
//! enabled runtime — so every vector failure is a named test failure
//! rather than a single opaque diff dump.

use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::process::Command;

use serde::{Deserialize, Serialize};

#[derive(Deserialize)]
struct PyOut {
    outputs: Vec<Option<serde_json::Value>>,
    final_stack: Vec<serde_json::Value>,
}

/// Parsed form of `inputs.json`.
#[derive(Debug, Clone, Deserialize)]
pub struct Inputs {
    /// Calldata values exposed to `INPUT` instructions in slot order.
    #[serde(default)]
    pub calldata: Vec<i64>,
    /// Number of output slots; defaults to 16 to match `xquad run`.
    #[serde(default = "default_output_slots")]
    pub output_slots: usize,
}

const fn default_output_slots() -> usize {
    16
}

/// Parsed form of `expected.json`. Outputs use `null` for unset slots so
/// the JSON representation is stable across runs.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub struct Expected {
    /// Expected output slots; `None` means the slot must be unset.
    pub outputs: Vec<Option<i64>>,
    /// Expected residual stack contents after HALT.
    #[serde(default)]
    pub final_stack: Vec<i64>,
}

/// Execution result in a form directly comparable to [`Expected`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Outcome {
    /// Output slot contents observed after execution.
    pub outputs: Vec<Option<i64>>,
    /// Residual stack contents after HALT.
    pub final_stack: Vec<i64>,
}

/// Loaded conformance vector with all on-disk artifacts materialised.
#[derive(Debug, Clone)]
pub struct Vector {
    /// Category bucket (`arithmetic`, `control-flow`, …).
    pub category: String,
    /// Vector name within the category.
    pub name: String,
    /// Absolute path to the vector directory on disk.
    pub dir: PathBuf,
    /// Contents of `program.xqasm`.
    pub program_xqasm: String,
    /// Parsed `inputs.json`.
    pub inputs: Inputs,
    /// Parsed `expected.json`.
    pub expected: Expected,
}

/// Resolve the `conformance/` root relative to the crate manifest dir.
fn conformance_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Load a vector by `<category>/<name>` relative path segments.
///
/// # Errors
/// Returns any I/O error reading the three required files, or a
/// [`io::Error`] wrapping a JSON parse failure for `inputs.json` or
/// `expected.json`.
pub fn load_vector(category: &str, name: &str) -> io::Result<Vector> {
    let dir = conformance_root().join("vectors").join(category).join(name);
    let program_xqasm = fs::read_to_string(dir.join("program.xqasm"))?;
    let inputs: Inputs = serde_json::from_str(&fs::read_to_string(dir.join("inputs.json"))?)
        .map_err(io::Error::other)?;
    let expected: Expected = serde_json::from_str(&fs::read_to_string(dir.join("expected.json"))?)
        .map_err(io::Error::other)?;
    Ok(Vector {
        category: category.to_owned(),
        name: name.to_owned(),
        dir,
        program_xqasm,
        inputs,
        expected,
    })
}

/// Execute the vector against the in-process Rust VM.
///
/// # Errors
/// Returns an error message if assembly, VM setup, or execution fails.
pub fn run_rust(vector: &Vector) -> Result<Outcome, String> {
    use xqvm::RegVal;

    let program = xqasm::assemble_source(&vector.program_xqasm)
        .map_err(|e| format!("assemble_source failed: {e}"))?;

    let calldata: Vec<RegVal> = vector
        .inputs
        .calldata
        .iter()
        .copied()
        .map(RegVal::Int)
        .collect();

    let outcome = run_rust_program(&program, &calldata, vector.inputs.output_slots)?;

    // Bytecode round-trip: encode → decode → execute and verify parity.
    let bytecode = program.encode();
    let decoded =
        xqvm::Program::decode(&bytecode).map_err(|e| format!("bytecode decode failed: {e:?}"))?;
    let bc_outcome = run_rust_program(&decoded, &calldata, vector.inputs.output_slots)?;
    if outcome != bc_outcome {
        return Err(format!(
            "Rust bytecode parity mismatch:\n  source:   {outcome:?}\n  bytecode: {bc_outcome:?}"
        ));
    }

    Ok(outcome)
}

fn run_rust_program(
    program: &xqvm::Program,
    calldata: &[xqvm::RegVal],
    output_slots: usize,
) -> Result<Outcome, String> {
    use xqvm::{RegVal, Vm};

    let mut vm = Vm::new();
    let _ = vm
        .set_calldata(calldata.to_vec())
        .set_output_slots(output_slots);

    vm.run(program)
        .map_err(|e| format!("vm.run failed: {e:?}"))?;

    let mut outputs: Vec<Option<i64>> = vm
        .outputs()
        .iter()
        .map(|rv| match rv {
            RegVal::Unset => None,
            RegVal::Int(n) => Some(*n),
            other => Some(fold_regval_to_i64(other)),
        })
        .collect();
    trim_trailing_unset(&mut outputs);
    let final_stack = vm.stack().to_vec();
    Ok(Outcome {
        outputs,
        final_stack,
    })
}

/// Drop trailing `None` entries so outputs report a sparse map rather than
/// a fixed-width array padded with `null`. A vector that writes only slot 0
/// out of 16 reserved slots thus produces `[value]`, not
/// `[value, null, null, …]` — matching `spec/xqvm/SPEC.md:46`.
fn trim_trailing_unset(outputs: &mut Vec<Option<i64>>) {
    while matches!(outputs.last(), Some(None)) {
        let _ = outputs.pop();
    }
}

/// Execute the vector against the Python reference VM.
///
/// Shells out via `uv run python -m xqvm_py run …` so the workspace
/// venv (with `xqvm_py` installed editable and the `xqffi` pyo3
/// extension built by maturin) is activated automatically. Override
/// the interpreter wrapper with `XQUAD_CONFORMANCE_PYTHON` (defaults
/// to `uv`).
///
/// # Errors
/// Returns an error message if the subprocess spawn fails, exits
/// non-zero, or produces output that is not valid UTF-8 JSON in the
/// expected schema.
pub fn run_python(vector: &Vector) -> Result<Outcome, String> {
    let runner = std::env::var("XQUAD_CONFORMANCE_PYTHON").unwrap_or_else(|_| "uv".into());
    let repo_root = conformance_root().join("..");

    let outcome = run_python_file(
        &runner,
        &repo_root,
        vector,
        &vector.dir.join("program.xqasm"),
    )?;

    // Bytecode round-trip: assemble → .xqb temp file → Python decoder path.
    let program = xqasm::assemble_source(&vector.program_xqasm)
        .map_err(|e| format!("assemble_source failed: {e}"))?;
    let bytecode = program.encode();

    let tmp = tempfile::Builder::new()
        .suffix(".xqb")
        .tempfile()
        .map_err(|e| format!("failed to create temp file: {e}"))?;
    fs::write(tmp.path(), &bytecode).map_err(|e| format!("failed to write temp .xqb: {e}"))?;

    let bc_outcome = run_python_file(&runner, &repo_root, vector, tmp.path())?;
    if outcome != bc_outcome {
        return Err(format!(
            "Python bytecode parity mismatch:\n  source:   {outcome:?}\n  bytecode: {bc_outcome:?}"
        ));
    }

    Ok(outcome)
}

fn run_python_file(
    runner: &str,
    repo_root: &std::path::Path,
    vector: &Vector,
    program_path: &std::path::Path,
) -> Result<Outcome, String> {
    let output = Command::new(runner)
        .args([
            "run",
            "--no-sync",
            "python",
            "-m",
            "xqvm_py",
            "run",
            "--inputs",
        ])
        .arg(vector.dir.join("inputs.json"))
        .args(["--outputs", &vector.inputs.output_slots.to_string()])
        .arg(program_path)
        .current_dir(repo_root)
        .output()
        .map_err(|e| format!("failed to spawn `{runner} run python -m xqvm_py`: {e}"))?;

    if !output.status.success() {
        return Err(format!(
            "`{runner} run python -m xqvm_py` exited {}: stderr: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    let stdout = std::str::from_utf8(&output.stdout)
        .map_err(|e| format!("python stdout was not UTF-8: {e}"))?;

    let parsed: PyOut = serde_json::from_str(stdout.trim())
        .map_err(|e| format!("failed to parse python stdout as JSON: {e}\n{stdout}"))?;

    let mut outputs: Vec<Option<i64>> = parsed
        .outputs
        .into_iter()
        .map(|v| v.and_then(|val| val.as_i64()))
        .collect();
    trim_trailing_unset(&mut outputs);
    let final_stack: Vec<i64> = parsed
        .final_stack
        .into_iter()
        .filter_map(|v| v.as_i64())
        .collect();

    Ok(Outcome {
        outputs,
        final_stack,
    })
}

fn fold_regval_to_i64(rv: &xqvm::RegVal) -> i64 {
    // Vectors, models, and samples are not currently represented as i64
    // outputs in the conformance format. Returning a sentinel keeps the
    // comparison logic uniform; vectors that produce non-scalar outputs
    // will already fail the deeper equality check and surface a clear
    // mismatch message.
    let _ = rv;
    i64::MIN
}

/// Compare an [`Outcome`] against an [`Expected`], returning a
/// multi-line diff on mismatch.
///
/// # Errors
/// Returns a human-readable diff when either the output slot vector or
/// the residual stack disagrees.
pub fn check(actual: &Outcome, expected: &Expected) -> Result<(), String> {
    if actual.outputs == expected.outputs && actual.final_stack == expected.final_stack {
        return Ok(());
    }
    let mut msg = String::from("conformance mismatch:\n");
    if actual.outputs != expected.outputs {
        let _ = writeln!(
            msg,
            "  outputs:\n    expected: {:?}\n    actual:   {:?}",
            expected.outputs, actual.outputs
        );
    }
    if actual.final_stack != expected.final_stack {
        let _ = writeln!(
            msg,
            "  final_stack:\n    expected: {:?}\n    actual:   {:?}",
            expected.final_stack, actual.final_stack
        );
    }
    Err(msg)
}

/// Selector for which runtime a caller wants to exercise.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Impl {
    /// In-process Rust runtime via [`xqvm::Vm`].
    Rust,
    /// Subprocess to `uv run python -m xqvm_py run`.
    Python,
}

/// End-to-end: load a vector, run the chosen impl, compare to expected.
/// The call site is a single-line test body; any failure panics with a
/// specific message.
///
/// # Panics
/// Panics when the vector cannot be loaded, the chosen runtime fails,
/// or the outcome diverges from `expected.json`.
#[expect(
    clippy::panic,
    reason = "test-harness entry point: panic is the expected failure channel for #[test]"
)]
pub fn check_vector(category: &str, name: &str, imp: Impl) {
    let vector = load_vector(category, name)
        .unwrap_or_else(|e| panic!("load_vector({category}/{name}): {e}"));

    let outcome = match imp {
        Impl::Rust => run_rust(&vector),
        Impl::Python => run_python(&vector),
    }
    .unwrap_or_else(|e| panic!("{imp:?} runner failed for {category}/{name}: {e}"));
    check(&outcome, &vector.expected)
        .unwrap_or_else(|e| panic!("[{imp:?}] {category}/{name}\n{e}"));
}
