default:
    image: rust:latest
    cache:
        key:
            files:
                - Cargo.lock
        paths:
            - .cargo/registry/
            - .cargo/git/
            - target/

variables:
    CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"

.install-deps: &install-deps
    - export PATH="${CARGO_HOME}/bin:${PATH}"
    - make deps

stages:
    - lint
    - test

# -- Formatting -------------------------------------------------------------

lint:fmt:
    stage: lint
    before_script:
        - *install-deps
    script:
        - make fmt-check

# -- Lints ------------------------------------------------------------------

lint:clippy:
    stage: lint
    before_script:
        - *install-deps
    script:
        - make lint-clippy

lint:rustdoc:
    stage: lint
    before_script:
        - *install-deps
    script:
        - make lint-doc

lint:deny:
    stage: lint
    before_script:
        - *install-deps
    script:
        - make lint-deny

# -- Tests ------------------------------------------------------------------

test:unit:
    stage: test
    before_script:
        - *install-deps
    script:
        - make test-unit

test:integration:
    stage: test
    before_script:
        - *install-deps
    script:
        - make test-integration
