// Copyright (C) 2026 Postquant Labs Incorporated
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Walks `conformance/vectors/<category>/<name>/` at build time and
//! generates one `#[test]` function per vector per runtime, written to
//! `$OUT_DIR/vector_tests_rust.rs` and `vector_tests_python.rs`. The
//! test files under `tests/` include these generated sources.
//!
//! Generating tests at build time lets `cargo test -p xquad-conformance`
//! surface each vector as a named, independently-schedulable test — a
//! single shell loop would collapse every failure into one opaque
//! `assert!` call with no per-vector granularity.

#![expect(
    clippy::expect_used,
    reason = "build scripts halt compilation on failure; panics are the idiomatic exit path"
)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use walkdir::WalkDir;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let vectors_dir = manifest_dir.join("vectors");

    println!("cargo:rerun-if-changed=vectors");
    // Rebuild tests when any file under vectors/ changes, not just when
    // the top-level directory's mtime changes.
    if vectors_dir.exists() {
        for entry in WalkDir::new(&vectors_dir)
            .into_iter()
            .filter_map(Result::ok)
            .filter(|e| e.file_type().is_file())
        {
            println!("cargo:rerun-if-changed={}", entry.path().display());
        }
    }

    let vectors = discover_vectors(&vectors_dir);
    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR");
    write_test_file(
        &Path::new(&out_dir).join("vector_tests_rust.rs"),
        &vectors,
        "Rust",
    );
    write_test_file(
        &Path::new(&out_dir).join("vector_tests_python.rs"),
        &vectors,
        "Python",
    );
}

fn discover_vectors(root: &Path) -> Vec<(String, String)> {
    if !root.exists() {
        return Vec::new();
    }
    let mut out = Vec::new();
    for category_entry in fs::read_dir(root).expect("read vectors/") {
        let category_entry = category_entry.expect("category entry");
        if !category_entry.file_type().expect("file_type").is_dir() {
            continue;
        }
        let category = category_entry
            .file_name()
            .into_string()
            .expect("category name utf-8");
        for vector_entry in fs::read_dir(category_entry.path()).expect("read category dir") {
            let vector_entry = vector_entry.expect("vector entry");
            if !vector_entry.file_type().expect("file_type").is_dir() {
                continue;
            }
            let name = vector_entry
                .file_name()
                .into_string()
                .expect("vector name utf-8");
            // Require the three canonical files; skip incomplete directories.
            let dir = vector_entry.path();
            if dir.join("program.xqasm").exists()
                && dir.join("inputs.json").exists()
                && dir.join("expected.json").exists()
            {
                out.push((category.clone(), name));
            }
        }
    }
    out.sort();
    out
}

fn write_test_file(path: &Path, vectors: &[(String, String)], imp: &str) {
    let mut body = String::new();
    body.push_str("// Auto-generated by conformance/build.rs. Do not edit.\n");
    body.push_str(
        "// Regenerate by modifying conformance/vectors/ and re-running `cargo build`.\n\n",
    );
    for (category, name) in vectors {
        let fn_name = format!("vector_{}_{}", sanitize(category), sanitize(name));
        writeln!(
            body,
            "#[test]\nfn {fn_name}() {{\n    xquad_conformance::check_vector(\"{category}\", \"{name}\", xquad_conformance::Impl::{imp});\n}}\n"
        )
        .expect("writing to a String cannot fail");
    }
    fs::write(path, body).expect("write generated test file");
}

/// Translate arbitrary path segments into Rust identifier syllables.
fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}
